### ISSUE TITLE
ToShortTypeName fails with 'ArgumentOutOfRangeException' for nested type inside generic class

### ISSUE THREAD

**Issue by julealgon** [phatboyg/Magnum#22]
Having a nested non generic type inside a generic static class passed to the ToShortTypeName extension method throws an exception on the .Substring call, because the .Name property on the type does NOT have a " ` " character even though the type is a generic type, because of it's outer class.

This is the same pattern used by MassTransit with the Consumer<T>.All / For / etc classes.

Here is an example:

```
static class Outer<T>
{
     class Inner {}
}

[TestMethod]
public void TestMethod1()
{
    var name = typeof (Outer<int>.Inner).ToShortTypeName();
}
```

**Comment by togakangaroo** [comment]
Any update? Ran into this using Mass Transit
