### ISSUE TITLE
.NET Standard Release

### ISSUE THREAD

**Issue by Jaben** [phatboyg/Magnum#29]
I still use this library and it appears plenty others do as well (~130 downloads a day). Any chance of a quick .NET Standard 2.0 dual target release?

Thanks!

**Comment by Jaben** [comment]
@phatboyg I take it that's a 'no'? :)

**Comment by phatboyg** [comment]
Magnum is no longer supported, most of it has been moved into other libraries used by MassTransit.

**Comment by Jaben** [comment]
Thanks for answering, Chris. What about the reflection stuff? I particularly like your FastInvoke stuff.

**Comment by phatboyg** [comment]
I don't think so, I found it better to using Activator.CreateInstance to create generic wrappers around non-generic interfaces to get that stuff to work significantly faster without all the reflection.
